### PR TITLE
Add support for alternate currencies based on the tenant

### PR DESCRIPTION
**Pull request by nerdenough**
This PR adds support to the boilerplate for multiple currencies, based on the tenant's settings. It adds a custom `CurrencyValue` component which builds on top of [react-intl](https://github.com/formatjs/react-intl)'s `FormattedNumber` component and [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat).

## Examples
I couldn't find a way to change my language and currency through my account, but hardcoding both into the app gives decent examples.

Locale `en`, currency `nok`:
image

Locale `nb-no`, currency `nok`:
image

Locale `en`, currency `nzd`:
image

Locale `en`, currency `btc`:
image

Locale `de`, currency `eur`:
image

## Notes
- I've currently locked `react-intl` to `3.0.0` due to formatjs/react-intl#1395.
- Probably need to look at better error handling and default local/currency if the tenant query fails.
- From what I can tell the `Intl.NumberFormat` functionality doesn't support special use cases like `,-` for NOK or `:-` for SEK. When the locale is `nb-NO` and currency is `NOK` the currency will be rendered as `kr 999,00`. When the locale is `en` the currency will be rendered as `NOK 999.00`.
- The original VAT amount was `vatAmount.toFixed(2)`. I have kept this value at 2dp for consistency but not sure if it's required.

### CODE REVIEW

**Comment by nerdenough** [comment]
Might need to leave the `minimumFractionDigitals` at its default (2dp for most currencies). Setting it to `0` results in values like this:
image

Whereas it would be more consistent to display like this:
image

**Comment by hakonkrogh** [comment]
Ideally, we would like the boilerplate to make one single request to the server to fetch all the data it needs for the first render. Performance FTW! This is why the existing query fetches the component data AND the top menu.

Can you move the query for fetching tenant info to the same query as well? And also, what kind of server timings are we getting if we do that?

**Comment by nerdenough** [comment]
Removing `next-i18next` in this PR as the removal depends on the `CurrencyValue` component as a replacement in some cases, which is required for #13.

**Comment by nerdenough** [comment]
Average timings (of 10):
Before: `6.4ms`
After: `7.23ms`

**Pull request merged**
