### PR TITLE
Replacing Apollo with Urql

### PR DESCRIPTION
**Pull request by hakonkrogh**
Everything needed to get Apollo to run is really big in size. Both bytes wise and execution time wise (especially for lower powered devices). I would like to offer a different GraphQL client as a part of our standard boilerplate, and the one that I think will do the job best is [https://npmjs.org/package/urql](Urql).

Just introducing this small change, the TTI score measured in Lighthouse dropped at least two seconds if not more (from around 4 seconds to 2 seconds)

@nerdenough Have a look through the changes and evaluate if this is something that makes sense for new developers. I don't want to scare newcomers to Graphql off, and using something else than Apollo (which everybody is using these days), might do just that. Also, Urql has a more naive caching approach, so we need to test that it does not affect the boilerplate in a negative way. We are using union types in our api, not sure if that has any affect on invalidations in the cache.

### CODE REVIEW

**Comment by nerdenough** [comment]
The package seems pretty decent, especially with that much of a performance increase, and it looks fairly easy to use.

The structure seems pretty similar to Apollo (with `@apollo/react-hooks`) so I don't think it would be difficult for newcomers to get started with, but because it doesn't have the name "Apollo" they might decide to use something else. Perhaps that's an option the CLI could tackle, e.g. "Use `urql` instead of Apollo?" or vice-versa to help with that in the future.

**Comment by nerdenough** [comment]
Just hitting a small issue when navigating between pages, it looks like `loading` is always undefined, and so the page errors when there is no `data` as well.

image

**Comment by hakonkrogh** [comment]
The navigation issue has been resolved now. Turns out the useQuery hook returns `fetching` consistently, which also what they use in the docs.

I've split the main query into two separate ones since urql the urql cache is a bit more naive than then one Apollo uses. Don't think we will take much of a performance hit since they are executed in parallel on both the custom server and the now version.

I also cleaned up a bit here and there only to realise that you have a tidy-up branch. Hope it does not conflict with your stuff.

**Comment by hakonkrogh** [comment]
Great, I'll merge it!

**Pull request merged**
