### PR TITLE
Enable Now V2 deployments

### LINKED ISSUE #13: Enable Now v2 deployments
This includes:

- Remove the i18next library. We'll add it back once next has [support for request middleware](https://github.com/zeit/next.js/issues/7208)
- Remove the server/ folder.
- Take a look at the login feature and see if it is possible to do using `getInitialProps` in pages/_app.js
- adding now.json to setup dynamic routing, see [this example](https://github.com/hakonkrogh/vaerhona/blob/master/now.json) this example for inspiration

### PR DESCRIPTION
**Pull request by nerdenough**
This PR enables the boilerplate to be deployed with Now V2. The changes include:
- [x] Added lambda functions within `pages/api` for deployments with Now
- [x] Adding dynamic routing within the `now.json` config file
- [x] Updating auth to work with the new lambda functions
- [x] Tidying up components that used `next-i18next`
- [x] Refactored `server` to be consistent with lambda functions and fix routing

Notes:
- Now V2 has issues with `mjml`, I have published a package `@nerdenough/mjml-ncc-bundle` which prebundles the latest version of `mjml` with `@zeit/ncc` to make it compatible.
- Now V2 has some issues with `next/dynamic` imports. While we would like to not use SSR for auth, this is currently not possible until Now supports this.

Closes #13

### CODE REVIEW

**Comment by nerdenough** [comment]
The most recent change dynamically imports the `AuthGate` component with `ssr: false`. The component has also been updated with state to handle both login and logout events.

`next build` now works correctly, allowing the Now deployment to "succeed". However, attempting to load the page results in an infinite `r.e is not a function` error which I am currently looking into. This also happens when running `next build && next start` locally instead of `now dev`.

Routing is also an issue with custom paths like `/telescopes/some-telescope` or `skateboards/some-skateboard`. Refreshing a page with such a url will result in a 404. With dynamic routing we could pass this path back to the index page, and reroute it to `/product` or `/folder` based on the type, but still investigating possibilities around how to distinguish them.

**Comment by hakonkrogh** [comment]
> Routing is also an issue with custom paths like `/telescopes/some-telescope` or `skateboards/some-skateboard`. Refreshing a page with such a url will result in a 404. With dynamic routing we could pass this path back to the index page, and reroute it to `/product` or `/folder` based on the type, but still investigating possibilities around how to distinguish them.

The only way to make this work locally would be to always run `now dev` instead of `next` afaik. The routing limitations of Next prohibits us to do a fully dynamic routing without the use of Now.

This makes me think of another thing. What if we would like to offer different hosting platforms, like AWS or Azure, and still offer dynamic routes?

**Comment by nerdenough** [comment]
I've currently reverted back to using SSR for auth as using the `next/dynamic` import for client-side rendering causes the `r.e is not a function` issue in the production build. I was digging into this for quite a while on Friday and haven't been able to find a decent solution yet. https://github.com/CrystallizeAPI/crystallize-frontend-boilerplate/pull/18/commits/76adab09cf9c3bb5c190473b3528bdb7dbd357a2

> This makes me think of another thing. What if we would like to offer different hosting platforms, like AWS or Azure, and still offer dynamic routes?

That's a good point about the routing and something I'm still looking into. Have been struggling to get Now's routing mapping correctly for products but hoping to get something working this morning.

**Comment by nerdenough** [comment]
After a lot of investigation I've decided to move the product/folder path from the root level of the path (e.g. `example.com/telescopes/some-telescope`) to be nested within a "catalog" page with the url `example.com/p/telescopes/some-telescope`. This allowed me to create a shared `CatalogPage` component which performs the query to fetch the tree data, and then renders the `ProductPage` or `FolderPage` based on the `type` of the first item in the tree.

I've shortened the route to `/p` for product, but open to renaming it to something else (like `/products`, `/catalog`, etc) to be less ambiguous.

Happy to change anything if there's a better solution 🙂

### Now

Now allows us to define routes as such:
```
{
  "src": "/p/([^/].+)",
  "dest": "/catalog?path=$1"
}
```
This will map anything trailing the `/p/` to the `path` query param of the catalog page.

The problem with mapping the original route structure of `example.com/telescopes/some-telescope` instead of `/p/telescopes/some-telescope` is that the regex then becomes a catch all for any path that doesn't match routes we've already defined in `now.json`. This means any files from `/static`, `/_next/static` and any other path would be rerouted to the catalog page unintentionally.

### Next

As of Next 9 there is support for dynamic routing through file names. For example, `pages/product/[id].js` would pass through `id` as a query param in the request in `getInitialProps`. This uses the same `path-to-regexp` library used by Express meaning there is the potential to allow nested dynamic routes (e.g. `/telescopes/some-telescope`).

However, Next's implementation only allows the dynamic routes to be defined via the file name within square brackets, e.g. `pages/product/[id].js` where `id` would match `/product/:id`. To support a path such as `/telescopes/some-telescope` the filename would have to include something like `[([^/].+)].js`, which isn't a valid filename.

If functionality is added to Next to allow dynamic routes to be defined within `next.config.js` this may become a valid option.

### Other Platforms

This current solution only adds routing for Now, but I don't think it would be a big issue for people to define their own routes on other platforms (copying what we have in `now.json`) for the time being.

**Comment by nerdenough** [comment]
Running into an issue with generating the magic link when deployed to production with Now. Investigating what's going wrong:

```
{"errorType":"Error","errorMessage":"Cannot find module '../lib/utils.js'","code":"MODULE_NOT_FOUND","stack":["Error: Cannot find module '../lib/utils.js'","    at Function.webpackEmptyContext [as resolve] (/var/task/page.js:27914:10)","    at /var/task/page.js:141985:60","    at Array.map (<anonymous>)","    at Object.w19Z (/var/task/page.js:141984:3)","    at __webpack_require__ (/var/task/page.js:23:31)","    at Object.HI7s (/var/task/page.js:37074:16)","    at __webpack_require__ (/var/task/page.js:23:31)","    at Object.3Qgs (/var/task/page.js:13629:21)","    at __webpack_require__ (/var/task/page.js:23:31)","    at Object.tADp (/var/task/page.js:137908:17)"]}
```

Aside from this error everything else should be good to go.

**Comment by nerdenough** [comment]
The issue with formatting the magic link email in production was due to an issue with Now and `mjml` having some nested dependency on `uglify-js`. Based on the discussion of a similar issue, I have published a new package (`@nerdenough/mjml-ncc-bundle`) which builds the `mjml` library with `@zeit/ncc` and import that in place of `mjml`. This works fine both in dev and production.

From the discussion on different threads it looks like the issue with `uglify-js` might be fixed in newer versions of `@now/node`, but we are still facing the issue with `@now/next`.

**Comment by hakonkrogh** [comment]
Trying out Now deployments, and they keep failing:
[https://zeit.co/crystallize/crystallize-frontend-boilerplate/p1r5sv8gw](https://zeit.co/crystallize/crystallize-frontend-boilerplate/p1r5sv8gw)

One other thing, using `now dev` I cannot render the home page

**Comment by nerdenough** [comment]
The deploy looks to be failing because it's running `npm run greet` on postinstall. Removing the `postinstall` script from the package.json should fix the deploy. The script is automatically removed from package.json after running the greeting script the first time so it shouldn't affect many users.

Strange about the `now dev` issue, I'll look into it in the morning - working correctly with the demo store and my own tenant.

**Comment by nerdenough** [comment]
I'm unable to replicate the issue of the homepage not rendering, both with my own tenant and the `demo` store.

@hakonkrogh which version of the now cli are you using (I'm on `16.1.2`)? Also does `npm run now-dev` have a different result to running `now dev` directly?

**Comment by hakonkrogh** [comment]
> I'm unable to replicate the issue of the homepage not rendering, both with my own tenant and the `demo` store.
> 
> @hakonkrogh which version of the now cli are you using (I'm on `16.1.2`)? Also does `npm run now-dev` have a different result to running `now dev` directly?

I was indeed running an older version of Now locally. The latest version resolves the issues :)

**Pull request merged**
